template_program = '''
import numpy as np


def crossover(target: np.ndarray, mutant: np.ndarray, CR: float,
              generation: int, max_generations: int,
              fitness_target: float, fitness_best: float) -> np.ndarray:
    """Return a Differential Evolution trial vector.

    Args:
        target: current individual.
        mutant: mutant vector generated by fixed DE/rand/1 mutation.
        CR: base crossover rate.
        generation: current zero-based generation.
        max_generations: total planned generations.
        fitness_target: objective value of target, lower is better.
        fitness_best: best objective value in the population.

    Returns:
        A trial vector with the same shape as target.
    """
    dim = len(target)
    mask = np.random.rand(dim) < CR
    mask[np.random.randint(dim)] = True
    return np.where(mask, mutant, target)
'''

task_description = (
    "Design a crossover operator for Differential Evolution on high-dimensional "
    "continuous black-box optimization. Mutation is fixed as DE/rand/1. The designed "
    "function combines a target vector and a mutant vector using the base crossover "
    "rate, generation progress, target fitness, and population-best fitness. The "
    "baseline is standard binomial crossover. Performance is measured by final "
    "objective value on 100-dimensional Sphere, Rastrigin, Ackley, Rosenbrock, and "
    "Griewank benchmarks."
)
